name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/cachix/install-nix-action
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --command 'spago --global-cache skip test'